spring.application.name=employee-api

spring.h2.console.enabled=true
jwt.secret=ThisIsANewSecretKeyThatWillKillAllOldTokensForReal12345
jwt.issuer=SpringSecurityJwtApp
jwt.expiration=60000
server.port=8081